import assert from 'node:assert/strict';
export async function verifyFundedCompute(db) {
 const owner='10000000-1111-4111-8111-111111111111', worker='20000000-1111-4111-8111-111111111111', node='30000000-1111-4111-8111-111111111111';
 const q=async(s,a=[]) => (await db.query(s,a)).rows[0]?.r;
 const denied=async(s,a,re)=>{await db.exec('savepoint denial');await assert.rejects(q(s,a),re);await db.exec('rollback to denial; release denial');};
 await db.exec('begin');
 try {
 await db.exec(`insert into auth.users(id) values('${owner}'),('${worker}'); insert into public.profiles(id,display_name) values('${owner}','Sponsor'),('${worker}','Worker'); insert into hive.members(id,status) values('${owner}','active'),('${worker}','active'); select set_config('request.jwt.claim.sub','${owner}',true); insert into hive.nodes(id,member_id,display_name,role,tos_version) values('${node}','${worker}','Worker','compute','test');`);
 const project=await q(`insert into hive.projects(owner_id,title,execution_mode) values($1,'Funded tests','hive') returning id r`,[owner]);
 const localProject=await q("insert into hive.projects(owner_id,title,execution_mode) values($1,'Private budget test','local') returning id r",[owner]);
 const localCard=await q("insert into hive.cards(project_id,key,title,modality) values($1,'private','Private','text') returning id r",[localProject]);
 await denied('select public.hive_compute_budget_status($1) r',[localCard],/community_card_not_found/);
 const fund=await q('select fund_account_id r from hive.projects where id=$1',[project]);
 const wallet=await q("select id r from hive.accounts where member_id=$1 and kind='member_wallet'",[owner]);
 const treasury=await q("select id r from hive.accounts where kind='treasury'");
 const mint=async(account)=>q('select hive.post_txn($1::jsonb,$2) r',[JSON.stringify([{account_id:treasury,direction:'debit',entry_type:'storage_charge',amount:10,source:'grant'},{account_id:account,direction:'credit',entry_type:'storage_charge',amount:10,source:'grant'}]),'Test fixture funding']);
 await mint(fund);await mint(wallet);
 const card=await q("insert into hive.cards(project_id,key,title,modality,inputs) values($1,'test','Test','text','hello') returning id r",[project]);
 const lease='insert into hive.leases(card_id,node_id,expires_at) values($1,$2,now()+interval \'10 minutes\') returning card_id r';
 await denied(lease,[card,node],/compute_budget_required/);
 await db.exec(`set local role authenticated; select set_config('request.jwt.claim.sub','${worker}',true)`);
 assert.equal((await q('select public.hive_compute_budget_status($1) r',[card])).can_approve,false);
 await denied('select public.hive_compute_budget_approve($1,1) r',[card],/not_owned_hive_card/);
 await db.exec(`select set_config('request.jwt.claim.sub','${owner}',true)`);
 assert.equal((await q('select public.hive_compute_budget_status($1) r',[card])).can_approve,true);
 await q('select public.hive_compute_budget_approve($1,1) r',[card]);
 const approved=await q('select public.hive_compute_budget_status($1) r',[card]);
 assert.equal(approved.approved,true); assert.equal(approved.can_approve,false); assert.equal(approved.funded,true);
 await db.exec('reset role');
 await q(lease,[card,node]);
 assert.equal(Number(await q('select sum(amount) r from hive.speech_reservations where card_id=$1',[card])),1);
 await denied("select hive.split_debit($1,10,array['grant'],'{}') r",[fund],/insufficient/);
 await db.exec(`select set_config('request.jwt.claim.sub','${worker}',true)`);
 const key=await q("select hive.mint_node_key($1,'test') r",[node]);
 await db.exec(`select set_config('request.jwt.claim.sub','${owner}',true)`);
 const complete='select hive.node_complete_card($1,$2,$3,$4,$5,$6,$7) r';
 await denied(complete,[key,card,'answer','test',0,1000000,1],/compute_budget_exceeded/);
 assert.equal(Number(await q('select count(*) r from hive.card_outputs where card_id=$1',[card])),0);
 await q(complete,[key,card,'answer','test',0,10,1]);
 assert.equal(Number(await q('select count(*) r from hive.speech_reservations where card_id=$1',[card])),0);
 assert.ok(Number(await q('select hive.account_balance($1) r',[fund]))<10);
 const remaining=Number(await q('select hive.compute_budget_remaining($1) r',[card]));
 assert.ok(remaining>0 && remaining<1);
 const status=await q('select public.hive_compute_budget_status($1) r',[card]);
 assert.equal(Number(status.remaining),remaining); assert.ok(Number(status.spent)>0);
 await q("update hive.cards set status='ready' where id=$1",[card]);
 await q(lease,[card,node]);
 assert.equal(Number(await q('select sum(amount) r from hive.speech_reservations where card_id=$1',[card])),remaining);
 await q('delete from hive.leases where card_id=$1',[card]);
 assert.equal(Number(await q('select count(*) r from hive.speech_reservations where card_id=$1',[card])),0);
 await q("update hive.cards set status='review' where id=$1",[card]);
 // Reapproval keeps lifetime spending and rejects stale, foreign and active requests.
 await q("update hive.cards set status='ready' where id=$1",[card]);
 await db.exec('set local role authenticated');
 const beforeReplace=await q('select public.hive_compute_budget_status($1) r',[card]);
 assert.equal(beforeReplace.can_replace,true);
 const replace='select public.hive_compute_budget_replace($1,$2,$3,$4) r';
 const args=[card,2,beforeReplace.approval_version,beforeReplace.input_hash];
 await db.exec(`select set_config('request.jwt.claim.sub','${worker}',true)`);
 await denied(replace,args,/not_owned_hive_card/);
 await db.exec(`select set_config('request.jwt.claim.sub','${owner}',true)`);
 await denied(replace,[card,0,beforeReplace.approval_version,beforeReplace.input_hash],/limit_must_exceed_spent/);
 await denied(replace,[card,2,beforeReplace.approval_version,'outdated'],/budget_changed_refresh_required/);
 await denied(replace,[localCard,2,beforeReplace.approval_version,beforeReplace.input_hash],/not_owned_hive_card/);
 // A validation failure after archiving/deleting must roll the entire replacement back.
 await denied(replace,[card,2.0000001,beforeReplace.approval_version,beforeReplace.input_hash],/invalid_compute_budget/);
 assert.equal(Number(await q('select count(*) r from hive.compute_budget_history where card_id=$1',[card])),0);
 assert.equal(Number((await q('select public.hive_compute_budget_status($1) r',[card])).max_honey),1);
 await q(replace,args);
 await denied(replace,args,/budget_changed_refresh_required/);
 const replaced=await q('select public.hive_compute_budget_status($1) r',[card]);
 assert.equal(Number(replaced.max_honey),2);
 assert.equal(Number(replaced.spent),Number(beforeReplace.spent));
 assert.equal(Number(replaced.remaining),2-Number(beforeReplace.spent));
 assert.equal(Number(await q('select count(*) r from hive.compute_budget_history where card_id=$1',[card])),1);
 await db.exec('reset role');
 await q(lease,[card,node]);
 await db.exec('set local role authenticated');
 await denied(replace,[card,3,replaced.approval_version,replaced.input_hash],/compute_card_already_started/);
 await db.exec('reset role');
 await q('delete from hive.leases where card_id=$1',[card]);
 await q("update hive.cards set inputs='changed requirements' where id=$1",[card]);
 const changed=await q('select public.hive_compute_budget_status($1) r',[card]);
 assert.equal(changed.valid,false);
 await db.exec('set local role authenticated');
 await q(replace,[card,3,changed.approval_version,changed.input_hash]);
 assert.equal((await q('select public.hive_compute_budget_status($1) r',[card])).valid,true);
 await db.exec('reset role');
 await q("update hive.cards set status='review' where id=$1",[card]);
 const treasuryBefore=await q('select hive.account_balance($1) r',[treasury]);
 await db.exec('set local role authenticated');
 const sent=await q("select public.hive_interview_send_funded(null,'Hello','chat',1) r");
 await db.exec('reset role');
 assert.equal(await q('select hive.account_balance($1) r',[treasury]),treasuryBefore);
 await q("insert into hive.cards(project_id,key,title,modality,priority) values($1,'unapproved','Unapproved queue head','text',1000)",[project]);
 await q("update hive.nodes set presence='checked_in', capabilities=jsonb_build_object('modalities',jsonb_build_array('text'),'models',jsonb_build_array(jsonb_build_object('id',(select required_capabilities->>'model_id' from hive.cards where id=$2)))) where id=$1",[node,sent.card_id]);
 const claimed=await q('select hive.node_claim_card($1) r',[key]);
 assert.equal(claimed.card.id,sent.card_id);
 await q(complete,[key,sent.card_id,'Hello back','test',0,10,1]);
 const paid=await q('select hive.account_balance($1) r',[wallet]);
 assert.ok(Number(paid)<10);
 await db.exec('set local role authenticated');
 await q('select hive_interview_poll($1) r',[sent.session_id]);
 await q('select hive_interview_poll($1) r',[sent.session_id]);
 await db.exec('reset role');
 assert.equal(await q('select hive.account_balance($1) r',[wallet]),paid);
 await db.exec(`insert into hive.regional_servers(node_id,status) values('${node}','online')`);
 await q("insert into hive.artifacts(hash,project_id,bytes) values('s4-storage',$1,1073741824)",[project]);
 await q("insert into hive.artifact_replicas(hash,node_id,bytes,announced_at) values('s4-storage',$1,1073741824,now()-interval '2 hours')",[node]);
 assert.equal(Number((await q('select hive.settle_storage() r')).paid),0);
 await db.exec('set local role authenticated');
 await q("select public.hive_storage_allowance_approve('s4-storage',$1,$2,0.001) r",[node,project]);
 await db.exec('reset role');
 await db.exec("update hive.storage_allowances set approved_at=now()-interval '2 hours'");
 const storage=await q('select hive.settle_storage() r');
 assert.ok(Number(storage.paid)>0 && Number(storage.paid)<=0.001*2/24);
 assert.equal(Number((await q('select hive.settle_storage() r')).paid),0);
 await db.exec("update hive.artifact_replicas set bytes=bytes*10,last_settled_at=now()-interval '2 hours'");
 assert.equal(Number((await q('select hive.settle_storage() r')).paid),0);
 assert.equal(await q('select hive.account_balance($1) r',[treasury]),treasuryBefore);
 await db.exec('set local role authenticated');
 const allowancePage=await q('select public.hive_project_storage_allowances($1,0) r',[project]);
 assert.equal(allowancePage.can_manage,true); assert.equal(allowancePage.replicas.length,1);
 assert.equal(allowancePage.replicas[0].size_matches,false);
 await denied('select public.hive_project_storage_allowances($1,0) r',[localProject],/community_project_not_found/);
 await db.exec(`select set_config('request.jwt.claim.sub','${worker}',true)`);
 assert.equal((await q('select public.hive_project_storage_allowances($1,0) r',[project])).can_manage,false);
 await denied("select public.hive_storage_allowance_revoke('s4-storage',$1) r",[node],/not_authorized_storage_sponsor/);
 await db.exec(`select set_config('request.jwt.claim.sub','${owner}',true)`);
 assert.equal((await q("select public.hive_storage_allowance_revoke('s4-storage',$1) r",[node])).revoked,true);
 assert.equal((await q("select public.hive_storage_allowance_revoke('s4-storage',$1) r",[node])).revoked,false);
 await db.exec('reset role');
 await db.exec("update hive.artifact_replicas set bytes=1073741824,last_settled_at=now()-interval '2 hours'");
 assert.equal(Number((await q('select hive.settle_storage() r')).paid),0);
 await q('select hive.ledger_integrity() r');
 console.log('PASS funded compute: approval, reservation, overspend rollback, settlement without polling, storage approval/cap/size/no mint, ledger integrity');
 } finally {await db.exec('rollback');}
}
