#!/usr/bin/env python3
"""Generate the Stage-1 scalar contract from committed Codex 0.149.0 schemas.

Only these supported types are generated; other payloads remain explicitly opaque.
Run after refreshing snapshots with the pinned runtime, then review the diff.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / 'crates/ohhive-core/src/subscription/schema/0.149.0'
OUTPUT = ROOT / 'crates/ohhive-core/src/subscription/generated.rs'


def string_type(prop, defs):
    if '$ref' in prop:
        return string_type(defs[prop['$ref'].split('/')[-1]], defs)
    if 'oneOf' in prop:
        assert all(string_type(x, defs) == ('String', False) for x in prop['oneOf'])
        return 'String', False
    if 'anyOf' in prop:
        values = [x for x in prop['anyOf'] if x.get('type') != 'null']
        assert len(values) == 1
        return string_type(values[0], defs)[0], len(values) != len(prop['anyOf'])
    kind = prop.get('type')
    nullable = isinstance(kind, list) and 'null' in kind
    if nullable:
        kind = next(x for x in kind if x != 'null')
    return {'string': 'String', 'boolean': 'bool'}[kind], nullable


def generate():
    ids = json.loads((FIXTURES / 'RequestId.json').read_text())
    assert ids['anyOf'] == [{'type': 'string'}, {'format': 'int64', 'type': 'integer'}]
    lines = ['// Generated by scripts/generate_codex_contract.py; do not edit.',
             '// Source: pinned Codex 0.149.0 JSON schemas. Other payloads remain opaque.',
             'use serde::{Deserialize, Serialize};', '',
             '#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]',
             '#[serde(untagged)]',
             'pub enum ServerRequestId { Text(String), Integer(i64) }', '']
    for name in ['AccountUpdatedNotification', 'AccountLoginCompletedNotification']:
        schema = json.loads((FIXTURES / f'{name}.json').read_text())
        lines += ['#[derive(Debug, Clone, Serialize, Deserialize)]', f'pub struct {name} {{']
        for key, prop in schema['properties'].items():
            typ, nullable = string_type(prop, schema.get('definitions', {}))
            optional = nullable or key not in schema.get('required', [])
            snake = ''.join('_' + c.lower() if c.isupper() else c for c in key)
            lines.append(f'    #[serde(rename = "{key}")]')
            lines.append(f'    pub {snake}: '+(f'Option<{typ}>' if optional else typ)+',')
        lines += ['}', '']
    return '\n'.join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    text = generate()
    manifest = json.loads((FIXTURES / 'manifest.json').read_text())
    for file, digest in manifest['sha256'].items():
        assert hashlib.sha256((FIXTURES / file).read_bytes()).hexdigest() == digest, file
    if args.check:
        assert OUTPUT.read_text() == text, 'generated.rs is stale'
        print('Pinned schema hashes and generated contract are current.')
    else:
        OUTPUT.write_text(text)


if __name__ == '__main__':
    main()
