// Generated by scripts/generate_codex_contract.py; do not edit.
// Source: pinned Codex 0.149.0 JSON schemas. Other payloads remain opaque.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ServerRequestId { Text(String), Integer(i64) }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccountUpdatedNotification {
    #[serde(rename = "authMode")]
    pub auth_mode: Option<String>,
    #[serde(rename = "planType")]
    pub plan_type: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccountLoginCompletedNotification {
    #[serde(rename = "error")]
    pub error: Option<String>,
    #[serde(rename = "loginId")]
    pub login_id: Option<String>,
    #[serde(rename = "onboardingEntrypoint")]
    pub onboarding_entrypoint: Option<String>,
    #[serde(rename = "success")]
    pub success: bool,
}
